### ISSUE TITLE
PHP 7.2 is moved to archive/ so it cannot be installed

### ISSUE THREAD

**Issue by janlazo** [ScoopInstaller/PHP#12]
https://windows.php.net/downloads/releases/ doesn't list `php-7.2.34-Win32-VC15-x64.zip` because it's moved to the `archive/` subdirectory.

https://windows.php.net/downloads/releases/archives/php-7.2.34-Win32-VC15-x64.zip is the new path.

**Comment by greenhat616** [comment]
@r15ch13 too

**Comment by niheaven** [comment]
Make a PR, and I could merge it.

**Comment by tech189** [comment]
I made a PR with the new `/archives/` URLs.
