### ISSUE TITLE
Disable Excavator and move to Actions

### ISSUE THREAD

**Issue by r15ch13** [ScoopInstaller/PHP#17]
This is the last Repo running the old Excavator. If someone could move this to Actions then I could decommission Excavator completely.

PS: Created an issue from the discussion, because the templates make it impossible to create a general issue...

**Comment by Calinou** [comment]
> PS: Created an issue from the discussion, because the templates make it impossible to create one...

Disallowing blank issues is only an UI tweak – it doesn't actually prevent people from using the empty issue form if they manually browse to it. For this repository, browsing to https://github.com/ScoopInstaller/PHP/issues/new (remove `/choose` at the end of the URL) should do the trick in this case.

**Comment by rasa** [comment]
See https://github.com/ScoopInstaller/PHP/commit/d37708e0531867744fd6ecd701969230fbf5ed4a and
https://github.com/ScoopInstaller/PHP/runs/6385096716?check_suite_focus=true
