### ISSUE TITLE
[BUG]: Auto-update file hash for php 8.1 fails

### ISSUE THREAD

**Issue by thomasvvugt** [ScoopInstaller/PHP#19]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

php/php8.1

### Expected/Current Behaviour

I am experiencing file hash mismatches when the packages auto-updates. It seems like the file hashes are not properly retrieved from the sha256hash text file.

### Steps to Reproduce

```console
scoop update php8.1
```

### Possible Solution

Maybe someone can confirm if the hash url is actually correct, this is currently:

```
"autoupdate": {
        "hash": {
            "url": "$baseurl/sha256sum.txt"
        }
    },
```

And this should point to: https://windows.php.net/downloads/releases/sha256sum.txt

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'main' bucket:
4ef5ea4b9 (HEAD -> master, origin/master, origin/HEAD) wget: Update to version 1.21.4

'php' bucket:
362392e (HEAD -> master, origin/master, origin/HEAD) php8.2: Update to version 8.2.6
```

### Scoop Config

```console
last_update         scoop_branch scoop_repo
-----------         ------------ ----------
11/05/2023 19:40:33 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment]
It's possible that the hash file is updated after the manifest fetches the hashes.
